[package]
name = "raw-window-handle"
version = "0.3.0"
authors = ["Osspial <osspial@gmail.com>"]
edition = "2018"
description = "Interoperability library for Rust Windowing applications."
license = "Unlicense"
repository = "https://github.com/rust-windowing/raw-window-handle"
keywords = ["windowing"]
readme = "README.md"
documentation = "https://docs.rs/raw-window-handle"

[badges]
travis-ci = { repository = "rust-windowing/raw-window-handle" }
appveyor = { repository = "rust-windowing/raw-window-handle" }

[dependencies]
libc = {version="0.2", features=[]}

[features]
nightly-docs = []

[package.metadata.docs.rs]
features = ["nightly-docs"]
