[package]
name = "raw-window-handle"
version = "0.1.0"
authors = ["Osspial <osspial@gmail.com>"]
edition = "2018"
description = "Raw platform window types for interoperability"
license = "Unlicense"
repository = "https://github.com/rust-windowing/raw-window-handle"
keywords = ["windowing"]

[dependencies]
libc = {version="0.2", features=[]}
